services:
  postgres:
    container_name: loom-app
    image: postgres:latest
    ports:
      - '5433:5433'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
